import { useEffect, useState } from 'react';
import { BookOpen, CheckCircle2, ClipboardCheck, FileText, Settings, Users } from 'lucide-react';
import { api } from '../lib/api';
import type { SessionUser } from '../types';

export default function AdminDashboard({ user }: { user: SessionUser }) {
  const [stats, setStats] = useState<any>(null); const [xp, setXp] = useState<any>(null); const [message, setMessage] = useState('');
  useEffect(() => { api.dashboard().then(setStats); if (user.role === 'owner') api.xpSettings().then(setXp); }, [user.role]);
  const cards = [['کل درس‌ها', stats?.lessons ?? '—', BookOpen], ['مسئله‌ها', stats?.problems ?? '—', FileText], ['مشارکت‌های در صف', stats?.pendingContributions ?? '—', CheckCircle2], ['مسئله‌های پیشنهادی', stats?.pendingProblems ?? '—', ClipboardCheck], ['حساب‌ها', stats?.users ?? '—', Users]] as const;
  async function saveXp() { await api.updateXpSettings(xp); setMessage('امتیازهای پایه ذخیره شد؛ امتیازهای قبلی دست‌نخورده می‌مانند.'); setTimeout(() => setMessage(''), 2500); }
  return <div><div className="mb-8"><div className="text-xs tracking-[.25em] uppercase text-blue-400/60 mb-2">Control Center</div><h1 className="text-3xl font-black text-white">سلام، {user.displayName}</h1><p className="text-slate-500 mt-2">هر تغییر رسمی از این پنل وارد کتابخانه‌ی CupHead می‌شود.</p></div><div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-4">{cards.map(([label, value, Icon]) => <div key={label} className="glass-card neon-hover rounded-2xl p-5"><div className="w-10 h-10 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center mb-4"><Icon size={19} className="text-blue-300" /></div><div className="text-3xl font-black text-white">{value}</div><div className="text-sm text-slate-500 mt-1">{label}</div></div>)}</div>{user.role === 'owner' && xp && <section className="glass-card rounded-2xl p-6 mt-6"><div className="flex items-center gap-2"><Settings size={18} className="text-cyan-300" /><h2 className="font-bold text-white">تنظیم XP مشارکت‌ها</h2></div><p className="text-sm text-slate-500 mt-2">این اعداد فقط برای مشارکت‌های پذیرفته‌شده‌ی بعدی استفاده می‌شوند.</p><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mt-5">{[['statement', 'صورت‌مسئله'], ['hint', 'راهنمایی'], ['solution', 'راه‌حل'], ['takeaway', 'نکته‌ی اصلی'], ['problem', 'مسئله']].map(([key, label]) => <label key={key} className="field-label">{label}<input type="number" className="input-ui mt-2" value={xp[key] ?? 0} onChange={e => setXp({ ...xp, [key]: Number(e.target.value) })} /></label>)}</div><div className="flex items-center gap-3 mt-5"><button onClick={saveXp} className="btn-primary">ذخیره XP</button>{message && <span className="text-sm text-cyan-200">{message}</span>}</div></section>}<div className="grid lg:grid-cols-2 gap-4 mt-6"><div className="glass-card rounded-2xl p-6"><h2 className="font-bold text-white mb-3">جریان رسمی محتوا</h2><div className="space-y-3 text-sm text-slate-400"><p>۱. کاربران عادی مشارکت یا مسئله‌ی جدید می‌فرستند.</p><p>۲. Admin آن‌ها را در صف بررسی می‌بیند.</p><p>۳. Admin و Headmaster می‌توانند محتوای رسمی خودشان را مستقیم منتشر کنند.</p><p>۴. XP هر مشارکت هنگام پذیرش ذخیره می‌شود و با تغییر نرخ‌های پایه، امتیازهای قبلی تغییر نمی‌کنند.</p></div></div><div className="glass-card rounded-2xl p-6"><h2 className="font-bold text-white mb-3">زیرساخت نسخه‌ی جدید</h2><div className="text-sm text-slate-400 leading-7">داده‌ها در SQLite با جدول‌های جدا برای مسئله‌ها، درس‌ها، مشارکت‌ها، درخواست‌ها و امتیازها نگهداری می‌شوند و برای توسعه‌ی آینده آماده‌اند.</div></div></div></div>;
}
