import { useEffect,useRef,useState } from 'react';
import { Copy, File, Trash2, Upload } from 'lucide-react';
import { api } from '../lib/api';
import type { SessionUser, UploadedFile } from '../types';
export default function FileManager({user}:{user:SessionUser}){
 const [files,setFiles]=useState<UploadedFile[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''); const ref=useRef<HTMLInputElement>(null); const canUpload=['owner','admin'].includes(user.role),canDelete=user.role==='owner';
 async function load(){setFiles(await api.files())} useEffect(()=>{load()},[]);
 async function upload(file?:File){if(!file)return;setBusy(true);try{await api.uploadFile(file);setMessage('آپلود شد.');await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('فایل حذف شود؟'))return;await api.deleteFile(id);await load()}
 return <div><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-7"><div><div className="text-xs tracking-[.25em] uppercase text-blue-400/60 mb-2">Assets</div><h1 className="text-3xl font-black text-white">فایل‌ها</h1><p className="text-slate-500 mt-2">تصویر، PDF، نمونه‌کد یا فایل کمکی را آپلود کنید و URL آن را در Markdown استفاده کنید.</p></div>{canUpload&&<><input ref={ref} type="file" className="hidden" onChange={e=>upload(e.target.files?.[0])}/><button disabled={busy} onClick={()=>ref.current?.click()} className="btn-primary"><Upload size={17}/>{busy?'در حال آپلود...':'آپلود فایل'}</button></>}</div>{message&&<div className="text-sm text-slate-400 mb-4">{message}</div>}
 <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{files.map(f=><div key={f.id} className="glass-card neon-hover rounded-2xl p-5"><div className="w-11 h-11 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center mb-4"><File size={20} className="text-blue-300"/></div><div className="font-bold text-slate-200 truncate" title={f.originalName}>{f.originalName}</div><div className="text-xs text-slate-600 mt-2">{Math.max(1,Math.round(f.size/1024))} KB · {f.mimetype||'file'}</div><div className="flex gap-2 mt-4"><a href={f.url} target="_blank" rel="noreferrer" className="btn-muted !py-2 !px-3 text-xs flex-1">باز کردن</a><button onClick={()=>navigator.clipboard.writeText(f.url)} className="btn-muted !p-2" title="Copy URL"><Copy size={15}/></button>{canDelete&&<button onClick={()=>remove(f.id)} className="btn-muted !p-2 !text-red-300"><Trash2 size={15}/></button>}</div></div>)}{files.length===0&&<div className="glass-card rounded-2xl p-10 text-center text-slate-500 md:col-span-2 xl:col-span-3">هنوز فایلی آپلود نشده است.</div>}</div>
 </div>
}
