import { useEffect,useMemo,useState } from 'react';
import { ArrowDown,ArrowUp,Plus,Save,Search,Trash2,X } from 'lucide-react';
import { api } from '../lib/api';
import type { Lesson,Rank,Roadmap,RoadmapModule,Section,SessionUser } from '../types';
import { confirmUnsavedChanges, useUnsavedChanges } from '../hooks/useUnsavedChanges';
const sections:[Section,string][]=[['programming','برنامه‌نویسی'],['algorithm','الگوریتم'],['theory','نظری']]; const ranks:[Rank,string][]=[['pawn','♟ پیاده'],['knight','♞ اسب'],['bishop','♝ فیل'],['rook','♜ رخ'],['queen','♛ وزیر'],['king','♚ شاه']];
export default function RoadmapEditor({user}:{user:SessionUser}){
 const [roadmap,setRoadmap]=useState<Roadmap|null>(null),[lessons,setLessons]=useState<Lesson[]>([]),[section,setSection]=useState<Section>('programming'),[rank,setRank]=useState<Rank>('pawn'),[lessonQuery,setLessonQuery]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[dirty,setDirty]=useState(false); const canEdit=['owner','admin'].includes(user.role);useUnsavedChanges(dirty);
 useEffect(()=>{Promise.all([api.getRoadmap(),api.adminLessons()]).then(([r,l])=>{setRoadmap(r);setLessons(l)}).catch((e:any)=>setError(e.message));},[]);
 const modules=roadmap?.[section][rank]||[]; const eligible=useMemo(()=>lessons.filter(l=>l.section===section&&l.rank===rank&&`${l.title} ${l.summary}`.toLowerCase().includes(lessonQuery.toLowerCase())),[lessons,section,rank,lessonQuery]);
 function setModules(next:RoadmapModule[]){if(!roadmap)return;setDirty(true);setRoadmap({...roadmap,[section]:{...roadmap[section],[rank]:next}})}
 function patch(i:number,p:Partial<RoadmapModule>){setModules(modules.map((m,x)=>x===i?{...m,...p}:m))}
 function move(i:number,d:number){const j=i+d;if(j<0||j>=modules.length)return;const a=[...modules];[a[i],a[j]]=[a[j],a[i]];setModules(a)}
 function addModule(){setModules([...modules,{id:`mod-${Date.now()}`,title:'ماژول جدید',description:'توضیح کوتاه ماژول',lessonIds:[]}])}
 function addLesson(mi:number,id:string){if(!id)return;const m=modules[mi];if(m.lessonIds.includes(id))return;patch(mi,{lessonIds:[...m.lessonIds,id]})}
 function moveLesson(mi:number,li:number,d:number){const ids=[...modules[mi].lessonIds],j=li+d;if(j<0||j>=ids.length)return;[ids[li],ids[j]]=[ids[j],ids[li]];patch(mi,{lessonIds:ids})}
 async function save(){if(!roadmap||!canEdit)return;setRoadmap(await api.saveRoadmap(roadmap));setDirty(false);setMessage('نقشه راه ذخیره شد.');setTimeout(()=>setMessage(''),1800)}
 if(error)return <div className="p-6 rounded-2xl border border-red-500/20 bg-red-500/10 text-red-300">خطا: {error}</div>;
 if(!roadmap)return <div className="text-slate-500">در حال بارگذاری...</div>;
 return <div><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-7"><div><div className="text-xs tracking-[.25em] uppercase text-blue-400/60 mb-2">Roadmap</div><h1 className="text-3xl font-black text-white">ویرایش نقشه راه</h1><p className="text-slate-500 mt-2">ماژول‌ها و ترتیب درس‌ها را بدون دست زدن به فایل‌های رابط تغییر دهید.</p></div>{canEdit&&<button onClick={save} className="btn-primary"><Save size={17}/> ذخیره</button>}</div>
 <div className="glass-card rounded-2xl p-4 mb-5 flex flex-wrap gap-3"><div className="flex gap-2">{sections.map(([id,label])=><button key={id} onClick={()=>{if(confirmUnsavedChanges()){setSection(id);setDirty(false)}}} className={`btn-muted !py-2 ${section===id?'!border-blue-500/30 !text-blue-200 !bg-blue-500/10':''}`}>{label}</button>)}</div><div className="w-px bg-dark-border hidden sm:block"/><div className="flex gap-2">{ranks.map(([id,label])=><button key={id} onClick={()=>{if(confirmUnsavedChanges()){setRank(id);setDirty(false)}}} className={`btn-muted !py-2 ${rank===id?'!border-blue-500/30 !text-blue-200':''}`}>{label}</button>)}</div>{message&&<span className="text-sm text-emerald-300 self-center">{message}</span>}</div>
 {!canEdit&&<div className="mb-4 p-4 rounded-xl border border-amber-500/20 bg-amber-500/5 text-amber-200 text-sm">نقش شما فقط اجازه مشاهده نقشه راه را دارد.</div>}
 <div className="space-y-4">{modules.map((m,mi)=><section key={m.id} className="glass-card rounded-2xl p-5"><div className="flex items-start gap-3"><div className="flex flex-col gap-1"><button disabled={!canEdit} onClick={()=>move(mi,-1)} className="btn-muted !p-2"><ArrowUp size={14}/></button><button disabled={!canEdit} onClick={()=>move(mi,1)} className="btn-muted !p-2"><ArrowDown size={14}/></button></div><div className="flex-1 grid md:grid-cols-2 gap-3"><input disabled={!canEdit} className="input-ui font-bold" value={m.title} onChange={e=>patch(mi,{title:e.target.value})}/><input disabled={!canEdit} className="input-ui" value={m.description} onChange={e=>patch(mi,{description:e.target.value})}/></div>{canEdit&&<button onClick={()=>setModules(modules.filter((_,i)=>i!==mi))} className="btn-muted !p-2 text-red-300"><Trash2 size={16}/></button>}</div>
  <div className="mt-5 space-y-2">{m.lessonIds.map((id,li)=>{const l=lessons.find(x=>x.id===id);return <div key={id} className="rounded-xl border border-dark-border bg-black/10 px-3 py-2 flex items-center gap-2"><span className="text-xs font-mono text-slate-600 w-6">{li+1}</span><span className="flex-1 text-sm text-slate-300">{l?.title||`درس حذف‌شده (${id})`}</span>{canEdit&&<><button onClick={()=>moveLesson(mi,li,-1)} className="text-slate-600 hover:text-white"><ArrowUp size={14}/></button><button onClick={()=>moveLesson(mi,li,1)} className="text-slate-600 hover:text-white"><ArrowDown size={14}/></button><button onClick={()=>patch(mi,{lessonIds:m.lessonIds.filter(x=>x!==id)})} className="text-slate-600 hover:text-red-300"><X size={15}/></button></>}</div>})}</div>
  {canEdit&&<div className="mt-4 grid sm:grid-cols-[1fr_1fr_auto] gap-2"><label className="relative"><Search size={15} className="absolute start-3 top-3 text-slate-500"/><input className="input-ui !ps-9" value={lessonQuery} onChange={e=>setLessonQuery(e.target.value)} placeholder="جست‌وجوی درس..."/></label><select id={`add-${mi}`} className="input-ui" defaultValue=""><option value="">افزودن درس...</option>{eligible.filter(l=>!m.lessonIds.includes(l.id)).map(l=><option key={l.id} value={l.id}>{l.title} ({l.status})</option>)}</select><button onClick={()=>{const el=document.getElementById(`add-${mi}`) as HTMLSelectElement;addLesson(mi,el.value);el.value=''}} className="btn-muted"><Plus size={16}/> افزودن</button></div>}
 </section>)}{canEdit&&<button onClick={addModule} className="w-full rounded-2xl border border-dashed border-slate-700 hover:border-blue-500/40 text-slate-500 hover:text-blue-300 p-5 transition flex items-center justify-center gap-2"><Plus size={18}/> ماژول جدید</button>}</div>
 </div>
}
