import { useEffect,useState } from 'react';
import { Medal,Trophy } from 'lucide-react';
import Navbar from './components/Navbar';
import Loading from './components/Loading';
import { api } from './lib/api';
import type { ScoreboardRow,XpSettings } from './types';
const labels=[['statements','ترجمه فارسی','statement'],['hints','راهنمایی','hint'],['solutions','راه‌حل','solution'],['takeaways','ایده اصلی','takeaway'],['problems','مسئله جدید','problem']] as const;
export default function ScoreboardPage(){const [rows,setRows]=useState<ScoreboardRow[]|null>(null);const [xp,setXp]=useState<XpSettings|null>(null);useEffect(()=>{Promise.all([api.scoreboard(),api.publicXpSettings()]).then(([r,x])=>{setRows(r);setXp(x)})},[]);return <div className="min-h-screen"><Navbar/>{!rows||!xp?<Loading/>:<main className="max-w-6xl mx-auto px-4 sm:px-6 py-10"><div className="text-center mb-9"><div className="eyebrow justify-center"><Trophy size={14}/> جدول مشارکت‌کنندگان</div><h1 className="text-3xl sm:text-5xl font-black text-white mt-3">امتیاز مشارکت کنندگان</h1><p className="text-slate-400 mt-3 max-w-2xl mx-auto">امتیاز هر مشارکت هنگام پذیرش جداگانه ثبت می‌شود؛ تغییر نرخ‌های پایه در آینده، امتیازهای قبلی را تغییر نمی‌دهد.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mb-6">{labels.map(([key,label,xpKey])=><div className="glass-card rounded-2xl p-4" key={key}><div className="text-xs text-slate-500">هر {label}</div><div className="text-2xl font-black text-cyan-200 mt-2">{xp[xpKey]} XP</div></div>)}</div><div className="glass-card rounded-3xl overflow-auto"><table className="scoreboard-table"><thead><tr><th>#</th><th>کاربر</th>{labels.map(([key,label])=><th key={key}>{label}</th>)}<th>XP نهایی</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id}><td>{i<3?<Medal size={17} className={i===0?'text-amber-300':i===1?'text-slate-300':'text-orange-300'}/>:i+1}</td><td><div className="flex items-center gap-3"><Avatar row={row}/><span className="font-bold text-slate-200">@{row.username}</span></div></td><td>{row.statements}</td><td>{row.hints}</td><td>{row.solutions}</td><td>{row.takeaways}</td><td>{row.problems}</td><td className="text-cyan-200 font-black">{row.xp}</td></tr>)}</tbody></table>{!rows.length&&<div className="p-12 text-center text-slate-500">هنوز مشارکت پذیرفته‌شده‌ای ثبت نشده است.</div>}</div></main>}</div>}
function Avatar({row}:{row:ScoreboardRow}){return row.profileImage==='/icon.png'?<img className="score-avatar" src="/icon.png" alt=""/>:<div className="score-avatar score-piece">{({pawn:'♟',knight:'♞',bishop:'♝',rook:'♜',queen:'♛',king:'♚'} as any)[row.profileImage||'pawn']||row.username.slice(0,1)}</div>}
